global:
  name: CNCF Interactive Landscape
  short_name: CNCF
  mode: CNCF
  repo: cncf/landscape
  website: 'https://landscape.cncf.io'
  short_domain: l.cncf.io
  company_url: 'https://www.cncf.io'
  email: info@cncf.io
  self: 'https://www.crunchbase.com/organization/cloud-native-computing-foundation'
  slack_channel: T08PSQ7BQ/BC07DVB0C/jqc0ANnvpVddAp651jgyMKdr
  meta:
    title: CNCF Cloud Native Interactive Landscape
    fb_admin: alex.contini.94
    description: 'Filter and sort by GitHub stars, funding, commits, contributors, hq location, and tweets'
    twitter: '@CloudNativeFdn'
    google_site_verification: 8l35EQriJXntsib5sBdRu4gmDV1nAP9PSoHccJC8ABQ
    ms_validate: 3AF9FFA12CCC3C49C0ABA71CCA222665
  membership: CNCF
twitter:
  search: landscape.cncf.io
  url: 'https://landscape.cncf.io'
  text: Cloud Native Landscape from @CloudNativefdn
relation:
  label: CNCF Relation
  url: cncf
  values:
    - id: hosted
      label: CNCF Projects
      children:
        - id: graduated
          label: CNCF Graduated Projects
          prefix: CNCF
          tag: Graduated Project
          color: '#3570af'
          big_picture_order: 1
          big_picture_label: CNCF Graduated
          big_picture_color: 'rgb(24,54,114)'
        - id: incubating
          label: CNCF Incubating Projects
          prefix: CNCF
          tag: Incubating Project
          color: '#00cbff'
          big_picture_order: 2
          big_picture_label: CNCF Incubating
          big_picture_color: 'rgb(83, 113, 189)'
        - id: sandbox
          label: CNCF Sandbox Projects
          prefix: CNCF
          tag: Sandbox Project
          color: '#d1f7ff'
          big_picture_label: CNCF Sandbox
          big_picture_color: 'rgb(108, 165, 209)'
          additional_relation: member
    - id: member
      label: CNCF Member Products/Projects
      tag: CNCF Member
    - id: false
      label: Non-CNCF Member Products/Projects
      url: 'no'
membership:
  Platinum:
    name: CNCF
    label: Platinum Member
    end_user_label: Platinum End User Member
    funding: Platinum
    is_large: true
  Gold:
    name: CNCF
    label: Gold Member
    end_user_label: Gold End User Member
    funding: Gold
    is_large: true
  Silver:
    name: CNCF
    label: Silver Member
    end_user_label: Silver End User Member
    funding: Silver
  Academic:
    name: CNCF
    label: Academic Member
    end_user_label: Academic End User Member
    funding: Academic
  Nonprofit:
    name: CNCF
    label: Nonprofit Member
    end_user_label: Nonprofit End User Member
    funding: Nonprofit
  End User Supporter:
    name: CNCF
    label: End User Supporter
    funding: End User Supporter
    enduser: true
  linux_foundation:
    name: LF
    label: Project
    funding: Linux Foundation
    crunchbase_and_children: 'https://www.crunchbase.com/organization/linux-foundation'
  cncf:
    name: CNCF
    label: Project
    funding: CNCF
  'false':
    funding: 'No'
home:
  header: >
    <h1>CNCF Cloud Native Interactive Landscape</h1> The Cloud Native Trail Map (<a target="_blank" rel="noopener noreferrer"
    href="https://raw.githubusercontent.com/cncf/trailmap/master/CNCF_TrailMap_latest.png">png</a>, <a target="_blank" rel="noopener noreferrer"
    href="https://raw.githubusercontent.com/cncf/trailmap/master/CNCF_TrailMap_latest.pdf">pdf</a>) is CNCF&apos;s recommended path through the cloud native
    landscape. The cloud native landscape (<a target="_blank" href="images/landscape.png">png</a>, <a target="_blank" href="images/landscape.pdf">pdf</a>),
    serverless landscape (<a target="_blank" href="images/serverless.png">png</a>, <a target="_blank" href="images/serverless.pdf">pdf</a>), and member
    landscape (<a target="_blank" href="images/members.png">png</a>, <a target="_blank" href="images/members.pdf">pdf</a>) are dynamically generated below.
  footer: |
    Crunchbase data is used under license from Crunchbase to CNCF.
ads:
  - url: 'https://events.linuxfoundation.org/kubecon-cloudnativecon-europe/?utm_source=cncf_landscape&utm_medium=web&utm_campaign=kccnceu20'
    image: /images/info1.jpg
    title: Kubecon + CloudNativeCon Europe 2020
presets:
  - url: /format=card-mode&grouping=no&license=open-source&sort=first-commit
    label: Cards by age
  - url: /license=open-source
    label: Open source landscape
  - url: /category=cncf-members&format=card-mode&grouping=category
    label: Member cards
  - url: /format=card-mode&grouping=no&sort=stars
    label: Cards by stars
  - url: '/format=card-mode&grouping=headquarters&headquarters=china,hong-kong,taiwan'
    label: Cards from China
  - url: '/format=card-mode&grouping=category&category=certified-kubernetes-distribution,certified-kubernetes-hosted,certified-kubernetes-installer,special'
    label: Certified K8s/KCSP/KTP
  - url: /format=card-mode&grouping=no&sort=amount
    label: Cards by MCap/Funding
big_picture:
  main:
    tab_index: -1
    url: landscape
    name: Landscape
    short_name: Land...
    title: CNCF Cloud Native Landscape
    fullscreen_header: Overwhelmed? Please see the CNCF Trail Map. That and the interactive landscape are at l.cncf.io
    elements:
      - type: HorizontalCategory
        category: Infrastructure
        rows: 6
        width: 1175
        height: 227
        top: 0
        left: 0
        color: 'rgb(109,61,143)'
      - type: HorizontalCategory
        category: Software Network Provider
        rows: 4
        width: 1175
        height: 162
        top: 236
        left: 0
        color: 'rgb(46,107,46)'
      - type: HorizontalCategory
        category: Edge Services
        rows: 4
        width: 1175
        height: 160
        top: 406
        left: 0
        color: 'rgb(143,88,61)'
test:
  header: CNCF Cloud Native Interactive Landscape
  section: CNCF Graduated Projects
  logo: kubernetes.svg
anonymous_organization:
  name: Non-Public Unnamed Organization
  homepage: 'https://www.cncf.io'
  city: Bouvet Island
  region: Antarctica
  country: Antarctica
  twitter: 'https://twitter.com/CloudNativeFdn'
mosaics:
  - cncf-logo.svg
  - landscape-logo.svg
